export const ADD_INPUT_ITEM = 'ADD_INPUT_ITEM';
export const EDIT_INPUT_ITEM = 'EDIT_INPUT_ITEM';
export const REMOVE_INPUT_ITEM = 'REMOVE_INPUT_ITEM';
export const REQUEST_SAVED_STATE = 'REQUEST_SAVED_STATE';
export const RECEIVE_SAVED_STATE = 'RECEIVE_SAVED_STATE';